image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  APP_HOST: autoquizz.com

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
after_script:
  - docker logout $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  tags:
    - docker-builder
  only:
    - master

deploy:
  stage: deploy
  script:
    - apk add --update bash openssh-client
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$CI_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$CI_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    - ssh root@206.189.14.224 "sudo docker pull $IMAGE_TAG"
    - ssh root@206.189.14.224 "sudo mkdir -p ~/$APP_HOST && sudo chmod a+rwx ~/$APP_HOST"
    - scp docker-compose.yml .env root@206.189.14.224:~/$APP_HOST
    - ssh root@206.189.14.224 "cd $APP_HOST && sudo docker-compose up -d"
    - ssh root@206.189.14.224 "sudo docker exec $APP_HOST npm run deploy"
  only:
    - master